blank_issues_enabled: false
contact_links:
  - name: 下载
    url: https://github.com/RawDiamondMC/Extra-Recipe-Fabric/releases
    about: 从Github下载模组
  - name: 下载2
    url: https://www.mcmod.cn/download/7424.html
    about: 从mcmod下载模组（可能不是最新版）
  - name: 模组页面
    url: https://www.mcmod.cn/class/7424.html
    about: 前往mcmod
  - name: Wiki
    url: https://github.com/YTXSY/ExtraRecipe-1.12.2-Forge/wiki
    about: 前往Wiki